spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagementsystem
    username: root
    password: Vikas/1998@



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

logging:
  level:
    root: INFO


management:
  endpoints:
    web:
      exposure:
        include: info,beans
